FROM node:14-alpine

RUN apk update && \
    apk add --no-cache \
    build-base \
    python3 \
    python3-dev \
    cairo-dev \
    pango-dev \
    jpeg-dev \
    giflib-dev

RUN ln -sf python3 /usr/bin/python

WORKDIR /app

COPY backend/package.json backend/package-lock.json ./

RUN npm install \
    && npm cache clean --force

COPY backend/ .

EXPOSE 8088

CMD ["node", "server.js"]
