FROM node:14-alpine

WORKDIR /app

COPY /backend/package.json /backend/package-lock.json ./

RUN apt-get update \
    && apt-get install -y python \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/* \
    && npm install \
    && npm cache clean --force

COPY /backend/ .

EXPOSE 8088

CMD ["node", "server.js"]

